spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://payments-database-service/payments
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update